name: Node.js App Deploy Automate CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install package
        run: npm install

      - name: Test the Application
        run: npm run check | tee test-results.txt

      - name: Upload The Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: test-results.txt

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Download the Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Test Results
          # path: test-results.txt

      - name: Display Test Results
        run: cat test-results.txt

      - name: Deploy the Application By PM2
        run: |
          ls -a
          pm2 status
          pm2 delete node-app || true
          pm2 start "npm start" --name "node-app" || { echo 'pm2 start failed'; exit 1; }
          pm2 save || { echo 'pm2 save failed'; exit 1; }
