name: Node.js App Deploy Automate CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install package
        run: npm install

      - name: Test the Application
        run: npm run check
